http_cache:
    enabled: true
    age: 10
    route:
        - homepage
        - product_list
        - block_category
        - block_news
        - block_search_product
        - block_garally
        - block_free
        - block_new_product
        - block_footer
        - block_logo
        - help_about
        - help_guide
        - help_privacy
        - help_tradelaw
        - help_agreement
